### ISSUE TITLE
Nitpick: On the Research page, the photos overlap into the next section sometimes

### ISSUE THREAD

**Issue by ebuescher** [Angie-B/Angie-B.github.io#5]
![image](https://user-images.githubusercontent.com/45406031/75387402-25c28600-5898-11ea-94ae-78c5b647b93f.png)

You can really see it if you zoom out:
![image](https://user-images.githubusercontent.com/45406031/75387470-44288180-5898-11ea-9475-51200f9eb5b5.png)

**Comment by Angie-B** [comment]
thats fine with me =)
